name: qbicc Docs no-op
on:
  push:
    paths:
      - '**.md'
      - '**.adoc'
    branches: [ main ]
  pull_request:
    paths:
      - '**.md'
      - '**.adoc'
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
jobs:
  build-linux:
    name: "Linux x86_64"
    runs-on: ubuntu-latest
    steps:
      - name: No-Op
        run: echo Done.
