name: QCC Docs no-op
on:
  push:
    paths:
      - '**.md'
      - '**.adoc'
    branches: [ master ]
  pull_request:
    paths:
      - '**.md'
      - '**.adoc'
    branches: [ master ]
    types: [ opened, synchronize, reopened ]
jobs:
  build-linux:
    name: "Linux Build AArch64"
    runs-on: [self-hosted, linux, arm64]
    steps:
      - name: No-Op
        run: echo Done.
