name: QCC Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened ]

jobs:
  build-linux:
    name: "Linux Build AArch64"
    runs-on: [self-hosted, linux, arm64]

    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Build with Maven
      run: mvn -B package --file pom.xml
